services:
  currency_db:
    container_name: currency_db
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5424:5432"
    volumes:
      - currency_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  currency_api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      currency_db:
        condition: service_healthy

volumes:
  currency_postgres_data: